# Generated by Django 5.2.7 on 2025-10-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='batch',
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='question',
            name='route',
            field=models.CharField(max_length=20, verbose_name='所屬市集'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
