# Generated by Django 5.2.7 on 2025-10-26 18:41

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_question_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.JSONField(default=trips.models.default_content),
        ),
    ]
