# Generated by Django 5.2.7 on 2025-10-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_icons/', verbose_name='Icon 圖片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, help_text='若需指定日期才填寫，否則可留空', null=True, verbose_name='日期'),
        ),
    ]
