# Generated by Django 5.2.7 on 2025-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_question_icon_image_alter_post_content2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手機號碼')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
