# Generated by Django 5.2.7 on 2025-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_manageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageuser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名稱'),
        ),
    ]
